version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
