name: Publish Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Patch package version
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          version=`npm version patch`
          echo "tag=$version" >> $GITHUB_ENV

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          npm version patch

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
